spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: anton.vtanke@gmail.com
    password: djmxhfvjgdjaurzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:family}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER:family}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  properties:
    hibernate:
    format_sql: true
app:
  security:
    refreshTokenDurationMs: 600000000
    jwtSecret: "======================FamilyApplication==========================="
    jwtExpirationMs: 1800000
    jwtCookie: "family-jwt"
    jwtRefreshCookie: "family-jwt-refresh"
